# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_templatecontainer', [dirname(__file__)])
        except ImportError:
            import _templatecontainer
            return _templatecontainer
        if fp is not None:
            try:
                _mod = imp.load_module('_templatecontainer', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _templatecontainer = swig_import_helper()
    del swig_import_helper
else:
    import _templatecontainer
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class TemplateContainerInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TemplateContainerInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TemplateContainerInt, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _templatecontainer.TemplateContainerInt_x_set
    __swig_getmethods__["x"] = _templatecontainer.TemplateContainerInt_x_get
    if _newclass:x = _swig_property(_templatecontainer.TemplateContainerInt_x_get, _templatecontainer.TemplateContainerInt_x_set)
    def __init__(self, *args): 
        this = _templatecontainer.new_TemplateContainerInt(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _templatecontainer.delete_TemplateContainerInt
    __del__ = lambda self : None;
TemplateContainerInt_swigregister = _templatecontainer.TemplateContainerInt_swigregister
TemplateContainerInt_swigregister(TemplateContainerInt)

class TemplateContainerDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TemplateContainerDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TemplateContainerDouble, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _templatecontainer.TemplateContainerDouble_x_set
    __swig_getmethods__["x"] = _templatecontainer.TemplateContainerDouble_x_get
    if _newclass:x = _swig_property(_templatecontainer.TemplateContainerDouble_x_get, _templatecontainer.TemplateContainerDouble_x_set)
    def __init__(self, *args): 
        this = _templatecontainer.new_TemplateContainerDouble(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _templatecontainer.delete_TemplateContainerDouble
    __del__ = lambda self : None;
TemplateContainerDouble_swigregister = _templatecontainer.TemplateContainerDouble_swigregister
TemplateContainerDouble_swigregister(TemplateContainerDouble)



